apiVersion: v1
kind: Service

metadata:
  name: kerberos

spec:
  selector:
    app: kerberos

  ports:
    - name: kdc
      protocol: TCP
      port: 88
      targetPort: 88

    - name: kadmin
      protocol: TCP
      port: 749
      targetPort: 749

  type: ClusterIP
