apiVersion: apps/v1
kind: Deployment

metadata:
  name: kerberos

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kerberos

  template:
    metadata:
      labels:
        app: kerberos

    spec:
      containers:
        - name: kerberos
          image: task-kerberos:latest

          ports:
            - containerPort: 88
            - containerPort: 749

          imagePullPolicy: Never

          env:
            - name: KRB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kerberos-admin
                  key: password
