apiVersion: v1
kind: Secret
metadata:
  name: taskapp-secrets
type: Opaque
stringData:
  kadmin-password: {{ .Values.kerberos.adminPassword | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
